name: Automated Blog Generator CI/CD

on:
  push:
    branches:
      - main

jobs:
  run-blog-generator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install --no-cache-dir -r requirements.txt

    - name: Run Blog Generation Pipeline
      env:
        PYTHONPATH: ./src    # Ensure src is in Python path
      run: python src/run_all.py

    - name: Upload generated outputs
      uses: actions/upload-artifact@v4
      with:
        name: generated-blogs
        path: outputs/
